version: 2.1

# Commands to share between jobs
commands:

  test:
    steps:
      - checkout
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - run:
          name: Build the site
          command: make build
      - run:
          name: Run the site
          command: bundle exec jekyll serve
          background: true
      - run:
          name: Wait for site to be ready
          command: sleep 5
      - run:
          name: Run Pa11y tests
          command: make test

  autocommit:
    steps:
      - checkout
      - run:
          name: Fetch component changes
          command: make fetch-component-data
      - run:
          name: Commit version changes
          command: >
            if [ ! "$(git status --porcelain)" == "" ]; then
              git config --global user.email "origami.support@ft.com";
              git config --global user.name "origamiserviceuser [bot]";
              git commit _data/components.json -m 'Update component data [ci skip]';
              git push origin master;
            fi

  install-dependencies:
    steps:
      - run:
          name: Install dependencies
          command: make install

  restore-dependencies:
    steps:
      - restore_cache:
          keys:
            - dependency-cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-gem{{ checksum "Gemfile.lock" }}-npm{{ checksum "package-lock.json" }}
            - dependency-cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-gem{{ checksum "Gemfile.lock" }}
            - dependency-cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
            - dependency-cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-master-gem{{ checksum "Gemfile.lock" }}-npm{{ checksum "package-lock.json" }}
            - dependency-cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-master-gem{{ checksum "Gemfile.lock" }}
            - dependency-cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-master

  cache-dependencies:
    steps:
      - save_cache:
          key: dependency-cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-gem{{ checksum "Gemfile.lock" }}-npm{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - vendor/bundle

# Circle jobs
jobs:

  # Verify code then run unit and integration tests
  test:
    docker:
      - image: circleci/ruby:2.4-node-browsers
    steps:
      - test

  # Fetch and commit component changes
  autocommit:
    docker:
      - image: circleci/ruby:2.4-node-browsers
    steps:
      - autocommit

# Circle workflows
workflows:
  version: 2
  test-and-autocommit:
    jobs:
      - test
      - autocommit:
          requires:
            - test
          filters:
            branches:
              only:
                - master
