version: 2

# References to reduce duplication in the rest of the config
references:
  container: &container_config
    docker:
      - image: circleci/ruby:2.4-node-browsers
  cache_dependencies: &cache_dependencies
    save_cache:
      key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      paths:
        - ~/.bundle
  restore_dependencies: &restore_dependencies
    restore_cache:
      keys:
        - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-v1-{{ arch }}-{{ .Branch }}-
        - gem-cache-v1-{{ arch }}-

# Circle jobs
jobs:

  # Verify code then run unit and integration tests
  test:
    <<: *container_config
    steps:
      - checkout
      - *restore_dependencies
      - run:
          name: Install dependencies
          command: make install
      - *cache_dependencies
      - run:
          name: Run the site
          command: make serve
          background: true
      - run:
          name: Wait for site to be ready
          command: sleep 1
      - run:
          name: Run Pa11y tests
          command: make test

  # Fetch and commit component changes
  autocommit:
    <<: *container_config
    steps:
      - checkout
      - *restore_dependencies
      - run:
          name: Fetch component changes
          command: make fetch-component-data
      - run:
          name: Commit version changes
          command: >
            if [ ! "$(git status --porcelain)" == "" ]; then
              git config --global user.email "origami.support@ft.com";
              git config --global user.name "origamiserviceuser [bot]";
              git commit _data/components.json -m 'Update component data [ci skip]';
              git push origin master;
            fi

# Circle workflows
workflows:
  version: 2
  test-and-autocommit:
    jobs:
      - test
      - autocommit:
          requires:
            - test
          filters:
            branches:
              only:
                - master
