name: Autocommit
on:
  push:
    branches:
      - master
jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.3
      with:
        node-version: 14.x
    - uses: actions/setup-ruby@v1.1.2
      with:
        ruby-version: '2.7'
    - run: make install
    - run: npm run build --if-present
    - name: Fetch component changes
      run: make fetch-component-data
    - name: Commit version changes
      run: |
        if [ ! "$(git status --porcelain)" == "" ]; then
          git config --global user.email "origami.support@ft.com";
          git config --global user.name "origamiserviceuser [bot]";
          git commit _data/components.json -m 'Update component data [ci skip]';
          git push origin master;
        fi
